spring:
  application:
    name: order
dubbo:
  protocol:
    name: dubbo
    port: 10010
  registry:
    address: nacos://${nacos.address:192.168.0.10}:8848?username=nacos&password=nacos
  application:
    qos-port: 22222
nacos:
  address: 192.168.91.8
