server:
  port: 9527
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: accountList #路由的ID，没有固定规则但要求唯一
          #uri: http://localhost:8000 #匹配后提供服务的路由地址
          uri: lb://service-provider #匹配后提供服务的路由地址
          predicates:
            - Path=/point  #断言，路径相匹配的进行路由
            - After=2021-04-08T02:07:37.164+08:00[Asia/Shanghai] #该时间后
          filters:
            - AddRequestHeader=X-Request-red, blue  #过滤器
            - AddRequestParameter=red, blue

eureka:
  instance:
    hostname: gateway  #主机名称
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: true #是否将自己注册到注册中心，默认 true
    fetch-registry: true  #是否从注册中心获取服务注册信息，默认 true
    registry-fetch-interval-seconds: 20 #从注册中心拉取服务列表时间间隔
    service-url:
      defaultZone: http://admin:123123@localhost:8761/eureka/
