server:
  port: 8003
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: product
          uri: lb://product
          predicates:
            - Path=/product/**
          filters:
            - RewritePath=/product/(?<path>.*),/$\{path}
        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order/(?<path>.*),/$\{path}
springdoc:
  swagger-ui:
    use-root-path: true
application:
  doc-services:
      - order
      - product
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "shutdown"
logging:
  level:
    com.xmg.filter.ApiLoggingFilter: debug
