server:
  port: 7001
spring:
  datasource:
    url: jdbc:mysql:///cloud-demo-provider?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root

logging:
  #日志级别 OFF、FATAL、ERROR、WARN、INFO、DEBUG、TRACE、 ALL
  level.root: info
  #日志输出文件目录
  #显示SQL
  level.org.hibernate.SQL: info