#spring:
#  application:
#    name: product
dubbo:
  application:
    name: product
    qos-port: 22286
  protocol:
    name: dubbo
    port: 10086
  registry:
    address: nacos://${nacos.address:192.168.0.10}:8848?username=nacos&password=nacos
    group: dubbo
nacos:
  address: 192.168.84.26
