spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/mybatis-start?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 1234

mybatis-plus:
  #config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true #是否开启驼峰命名自动映射
server:
  port: 8003
debug: true
